<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>DemoData</RootNamespace>
    <AssemblyTitle>DemoData</AssemblyTitle>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta7.25380.108" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.14.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Data\Data.csproj" />
    <ProjectReference Include="..\Export\Export.csproj" />
  </ItemGroup>
</Project>