<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>DemoData</RootNamespace>
        <AssemblyTitle>Data</AssemblyTitle>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
</Project>